### ISSUE TITLE
[Documentation] Clarify in the main README which gtk version is used please.

### ISSUE THREAD

**Issue by rubyFeedback** [ralph-schleicher/atmosphere-calculator#1]
Hey there,

You use a screenshot in the README which is nice - that way users can quickly
see how it looks. This is a good idea.

However had, from the image itself I am not entirely certain which gtk version
is in use. I assume gtk3 but I remember that in gtk2 this can probably also
be produced - so if it would be possible, could the main README mention
which gtk version is supported specifically? A simple version should suffice
perfectly. Thank you for reading this suggestion.

**Comment by ralph-schleicher** [comment]
The current version of the CL-CFFI-GTK library is based on GTK+ 3. One click on the CL-CFFI-GTK link clearifies this. I see no need to duplicate this information in the README.
